#ifndef MY_SPI_H
#define MY_SPI_H

#include "system.h"

#define AD9833_SPI_SCK_H HAL_GPIO_WritePin(GPIOH, GPIO_PIN_14, GPIO_PIN_SET)
#define AD9833_SPI_SCK_L HAL_GPIO_WritePin(GPIOH, GPIO_PIN_14, GPIO_PIN_RESET)
#define AD9833_SPI_SDA_H HAL_GPIO_WritePin(GPIOH, GPIO_PIN_12, GPIO_PIN_SET)
#define AD9833_SPI_SDA_L HAL_GPIO_WritePin(GPIOH, GPIO_PIN_12, GPIO_PIN_RESET)
#define AD9833_SPI_CS_H HAL_GPIO_WritePin(GPIOH, GPIO_PIN_11, GPIO_PIN_SET)
#define AD9833_SPI_CS_L HAL_GPIO_WritePin(GPIOH, GPIO_PIN_11, GPIO_PIN_RESET)

void AD9833_SPI_16bits_Write(uint16_t data);

#endif // MY_SPI_H